
const char* vs_2d = "#version 330 core\n"
                    "layout (location = 0) in vec3 aPos;\n"
                    "layout (location = 1) in vec3 aColor;\n"
                    "layout (location = 2) in vec2 aTexCoord;\n"
                    "out vec2 TexCoord;\n"
                    "void main()\n"
                    "{\n"
                    "   gl_Position = vec4(aPos.x, aPos.y, aPos.z, 1.0);\n"
                    "   TexCoord = aTexCoord;\n"
                    "}\0";
const char* fs_2d = "#version 330 core\n"
                    "in vec2 TexCoord;\n"
                    "uniform sampler2D ourTexture;\n"
                    "layout (location = 0) out vec4 FragColor;\n"

                    "void main()\n"
                    "{\n"
                    "   FragColor = texture(ourTexture, TexCoord);\n"
                    "   FragColor.a = 1.0;\n"
                    "}\n\0";

const char* fs_2d_trans = "#version 330 core\n"
                          "in vec2 TexCoord;\n"
                          "uniform sampler2D ourTexture;\n"
                          "layout (location = 0) out vec4 FragColor;\n"

                          "void main()\n"
                          "{\n"
                          "   FragColor = texture(ourTexture, TexCoord);\n"
                          //"   FragColor.a = 1.0;\n"
                          //   "   if (FragColor.r == 0 && FragColor.g == 0 && FragColor.b == 0) {\n"
                          //   "     discard;\n"
                          //   "   }\n"
                          "}\n\0";

const char* fs_postprocess = "#version 330 core\n"
                             "in vec2 TexCoord;\n"
                             "uniform vec4 color;\n"
                             "layout (location = 0) out vec4 FragColor;\n"

                             "void main()\n"
                             "{\n"
                             "   FragColor = color;\n"
                             "}\n\0";

// const char* vs_3d = "#version 330 core\n"
//                     "layout (location = 0) in vec3 aPos;\n"
//                     "layout (location = 1) in vec3 aNormal;\n"
//                     "\n"
//                     "out vec3 Normal;\n"
//                     "\n"
//                     "uniform mat4 model;\n"
//                     "uniform mat4 view;\n"
//                     "uniform mat4 projection;\n"
//                     "void main()\n"
//                     "{\n"
//                     "   Normal = aNormal;\n"
//                     "   gl_Position = projection * view * model * vec4(aPos,1);\n"
//                     "}\0";

// const char* fs_3d = "#version 330 core\n"
//                     "in vec3 Normal;\n"
//                     "\n"
//                     "out vec4 FragColor;\n"
//                     "\n"
//                     "uniform vec3 lightPos;\n"
//                     "uniform vec3 lightColor;\n"
//                     "uniform vec3 objectColor;\n"
//                     "void main()\n"
//                     "{\n"
//                     "    vec3 normal2 = normalize(Normal);\n"
//                     "    float light = dot(normal2, normalize(lightPos));\n"
//                     "    FragColor = vec4(1,1,1,1);\n"
//                     "    FragColor.rgb *= light;\n"
//                     "}\n\0";

const char* vs_3d = "#version 330 core\n"
                    "layout (location = 0) in vec3 aPos;\n"
                    "layout (location = 1) in vec3 aNormal;\n"
                    "layout (location = 2) in vec2 aUV;\n"
                    "\n"
                    "out vec3 FragPos;\n"
                    "out vec3 Normal;\n"
                    "out vec2 UV;\n"
                    "\n"
                    "uniform mat4 model;\n"
                    "uniform mat4 view;\n"
                    "uniform mat4 projection;\n"
                    "void main()\n"
                    "{\n"
                    "   FragPos = vec3(model * vec4(aPos, 1.0));\n"
                    "   Normal = aNormal;\n"
                    "   UV = aUV;\n"
                    "   gl_Position = projection * view * vec4(FragPos, 1.0);\n"
                    "}\0";

const char* fs_3d = "#version 330 core\n"
                    "in vec3 Normal;\n"
                    "in vec3 FragPos;\n"
                    "in vec2 UV;\n"
                    "\n"
                    "out vec4 FragColor;\n"
                    "\n"
                    "uniform vec3 lightPos;\n"
                    "uniform vec3 lightColor;\n"
                    "uniform vec3 objectColor;\n"
                    "uniform sampler2D tex;\n"
                    "uniform int textureSample = 1;\n"
                    "uniform vec4 clip_plane[6];\n"
                    "uniform int clip_plane_enabled[6];\n"
                    "void main()\n"
                    "{\n"
                    "  for(int i=0; i<6; i++) {\n"
                    "    if (clip_plane_enabled[i] == 1) {\n"
                    "      // calculate signed plane-vertex distance\n"
                    "      vec4 v4 = vec4(FragPos.x, FragPos.y, FragPos.z, 1);\n"
                    "      float d = dot(clip_plane[i], v4);\n"
                    "      if(d < 0.0) discard;\n"
                    "    }\n"
                    "  }\n"
                    "    if (textureSample == 1) {"
                    "       FragColor = texture(tex, UV);\n"
                    "    }\n"
                    "    else {\n"
                    "       FragColor = vec4(0,0,0,1);\n"
                    "    }\n"
                    "    FragColor.a = 1.0;\n"
                    "}\n\0";
