
const char* vs_2d = "#version 330 core\n"
                    "layout (location = 0) in vec3 aPos;\n"
                    "layout (location = 1) in vec3 aColor;\n"
                    "layout (location = 2) in vec2 aTexCoord;\n"
                    "out vec2 TexCoord;\n"
                    "void main()\n"
                    "{\n"
                    "   gl_Position = vec4(aPos.x, aPos.y, aPos.z, 1.0);\n"
                    "   TexCoord = aTexCoord;\n"
                    "}\0";

const char* fs_2d = "#version 330 core\n"
                    "in vec2 TexCoord;\n"
                    "uniform usampler2D pixels;\n"
                    "uniform sampler2D palette;\n"
                    "layout (location = 0) out vec4 FragColor;\n"

                    "void main()\n"
                    "{\n"
                    "   uint palette_index = texture(pixels, TexCoord.xy).x;\n"
                    "  vec4 texel = texelFetch(palette, ivec2(palette_index, 0), 0);\n"
                    "  FragColor = texel;\n"
                    " //}\n"
                    "}\n\0";

const char* fs_postprocess = "#version 330 core\n"
                             "in vec2 TexCoord;\n"
                             "uniform sampler2D pixels;\n"
                             "out vec4 FragColor;\n"

                             "void main()\n"
                             "{\n"
                             "   FragColor = texture(pixels, TexCoord);\n"
                             "}\n\0";

// const char* vs_3d = "#version 330 core\n"
//                     "layout (location = 0) in vec3 aPos;\n"
//                     "layout (location = 1) in vec3 aNormal;\n"
//                     "\n"
//                     "out vec3 Normal;\n"
//                     "\n"
//                     "uniform mat4 model;\n"
//                     "uniform mat4 view;\n"
//                     "uniform mat4 projection;\n"
//                     "void main()\n"
//                     "{\n"
//                     "   Normal = aNormal;\n"
//                     "   gl_Position = projection * view * model * vec4(aPos,1);\n"
//                     "}\0";

// const char* fs_3d = "#version 330 core\n"
//                     "in vec3 Normal;\n"
//                     "\n"
//                     "out vec4 FragColor;\n"
//                     "\n"
//                     "uniform vec3 lightPos;\n"
//                     "uniform vec3 lightColor;\n"
//                     "uniform vec3 objectColor;\n"
//                     "void main()\n"
//                     "{\n"
//                     "    vec3 normal2 = normalize(Normal);\n"
//                     "    float light = dot(normal2, normalize(lightPos));\n"
//                     "    FragColor = vec4(1,1,1,1);\n"
//                     "    FragColor.rgb *= light;\n"
//                     "}\n\0";

const char* vs_3d = "#version 330 core\n"
                    "layout (location = 0) in vec3 aPos;\n"
                    "layout (location = 1) in vec3 aNormal;\n"
                    "layout (location = 2) in vec2 aUV;\n"
                    "\n"
                    "out vec3 FragPos;\n"
                    "out vec3 Normal;\n"
                    "out vec2 TexCoord;\n"
                    "\n"
                    "uniform mat4 model;\n"
                    "uniform mat4 view;\n"
                    "uniform mat4 projection;\n"
                    "void main()\n"
                    "{\n"
                    "   FragPos = vec3(model * vec4(aPos, 1.0));\n"
                    "   Normal = aNormal;\n"
                    "   TexCoord = aUV;\n"
                    "   gl_Position = projection * view * vec4(FragPos, 1.0);\n"
                    "}\0";

const char* fs_3d = "#version 330 core\n"
                    "in vec3 Normal;\n"
                    "in vec3 FragPos;\n"
                    "in vec2 TexCoord;\n"
                    "\n"
                    "out int palette_index;\n"
                    "\n"
                    "uniform usampler2D pixels;\n"
                    "uniform sampler2D palette;\n"
                    "uniform int textureSample = 1;\n"
                    "uniform vec4 clip_planes[6];\n"
                    "uniform int clip_plane_count = 0;\n"
                    "void main()\n"
                    "{\n"
                    "  for(int i=0; i<clip_plane_count; i++) {\n"
                    "      // calculate signed plane-vertex distance\n"
                    "      vec4 v4 = vec4(FragPos.x, FragPos.y, FragPos.z, 1);\n"
                    "      float d = dot(clip_planes[i], v4);\n"
                    "      if(d < 0.0) discard;\n"
                    "  }\n"
                    "    if (textureSample == 1) {"
                    "       palette_index = texture(pixels, TexCoord.xy).x;\n"
                    "       //vec4 texel = texelFetch(palette, ivec2(palette_index, 0), 0);\n"
                    "       //FragColor = texel;\n"
                    "    }\n"
                    "    else {\n"
                    "        palette_index = 15;\n"
                    "    }\n"
                    "}\n\0";
