install(FILES LICENSE
    DESTINATION "${CMAKE_INSTALL_DOCDIR}"
)

set(DETHRACE_PACKAGE_PLATFORM "" CACHE STRING "Dethrace binary package platform")
set(DETHRACE_PACKAGE_ARCH "" CACHE STRING "Dethrace binary package architecture")

if(NOT DETHRACE_PACKAGE_PLATFORM)
    set(DETHRACE_PACKAGE_PLATFORM "${CMAKE_SYSTEM_NAME}")
endif()

string(TOLOWER "${DETHRACE_PACKAGE_PLATFORM}" DETHRACE_PACKAGE_PLATFORM)
string(TOLOWER "${DETHRACE_PACKAGE_ARCH}" DETHRACE_PACKAGE_ARCH)

set(CPACK_PACKAGE_NAME "dethrace")
set(CPACK_SYSTEM_NAME "${DETHRACE_PACKAGE_PLATFORM}")

set(CPACK_PACKAGE_FILE_NAME "dethrace-${DETHRACE_VERSION}-${DETHRACE_PACKAGE_PLATFORM}")

if(DETHRACE_PACKAGE_ARCH)
    string(APPEND CPACK_PACKAGE_FILE_NAME "-${DETHRACE_PACKAGE_ARCH}")
endif()

set(CPACK_PACKAGE_DIRECTORY dist)

if(NOT CPACK_GENERATOR)
    if(APPLE)
        set(CPACK_DMG_DISABLE_APPLICATIONS_SYMLINK "ON")
        set(CPACK_GENERATOR "DragNDrop")
        set(ext ".dmg")
    elseif(MSVC)
        set(CPACK_GENERATOR ZIP)
        set(ext ".zip")
    else()
        set(CPACK_GENERATOR "TGZ")
        set(ext ".tar.gz")
    endif()
endif()

set(CPACK_STRIP_FILES TRUE)

set(CPACK_DEBIAN_FILE_NAME "dethrace_${DETHRACE_VERSION}")
if(DETHRACE_PACKAGE_ARCH)
    string(APPEND CPACK_DEBIAN_FILE_NAME "_${DETHRACE_PACKAGE_ARCH}")
endif()
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Dethrace-Labs")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "3D Racing/Destruction Derby")
set(CPACK_DEBIAN_PACKAGE_SECTION "games")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE ${TARGET_ARCH})
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

set(CPACK_RPM_FILE_NAME "dethrace-${DETHRACE_VERSION}")
if(DETHRACE_PACKAGE_ARCH)
    string(APPEND CPACK_RPM_FILE_NAME ".${DETHRACE_PACKAGE_ARCH}")
endif()
set(CPACK_RPM_PACKAGE_LICENSE "GPLv3")
set(CPACK_RPM_PACKAGE_VENDOR "Dethrace-Labs")

if(EXISTS "$ENV{GITHUB_OUTPUT}")
    file(APPEND "$ENV{GITHUB_OUTPUT}" "filename=${CPACK_PACKAGE_FILE_NAME}${ext}")
endif()

include(CPack)