name: CI

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: make install-deps
    - name: build
      run: make build
    - name: test
      run: make test
