name: reccmp workload

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  reccmp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: dethrace-labs/reccmp-action@main
      with:
        cmake_flags: -G Ninja -DCMAKE_BUILD_TYPE=Debug -DMSVC_42_FOR_RECCMP=on
        target: CARM95
        report_filename: reccmp/reccmp-report.json
        original_binary_url: https://archive.org/download/carm-95/CARM95.EXE
        original_binary_filename: CARM95.EXE
